// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CardController from "./card_controller"
application.register("card", CardController)

import DragController from "./drag_controller"
application.register("drag", DragController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EventFormController from "./event_form_controller"
application.register("event-form", EventFormController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HeightController from "./height_controller"
application.register("height", HeightController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import RoomController from "./room_controller"
application.register("room", RoomController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)
