// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__ButtonController from "./bridge/button_controller"
application.register("bridge--button", Bridge__ButtonController)

import Bridge__VibrateController from "./bridge/vibrate_controller"
application.register("bridge--vibrate", Bridge__VibrateController)

import CardController from "./card_controller"
application.register("card", CardController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DebugController from "./debug_controller"
application.register("debug", DebugController)

import DistanceController from "./distance_controller"
application.register("distance", DistanceController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EntranceController from "./entrance_controller"
application.register("entrance", EntranceController)

import FieldErrorsController from "./field_errors_controller"
application.register("field-errors", FieldErrorsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GrowingTextareaController from "./growing_textarea_controller"
application.register("growing-textarea", GrowingTextareaController)

import HeightController from "./height_controller"
application.register("height", HeightController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import NotificationGranterController from "./notification_granter_controller"
application.register("notification-granter", NotificationGranterController)

import PasswordResetEmailController from "./password_reset_email_controller"
application.register("password-reset-email", PasswordResetEmailController)

import PhotosController from "./photos_controller"
application.register("photos", PhotosController)

import ReadableController from "./readable_controller"
application.register("readable", ReadableController)

import ReplaceClassesController from "./replace_classes_controller"
application.register("replace-classes", ReplaceClassesController)

import RoomController from "./room_controller"
application.register("room", RoomController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)
