// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Bridge__ButtonController from "./bridge/button_controller"
application.register("bridge--button", Bridge__ButtonController)

import Bridge__HapticController from "./bridge/haptic_controller"
application.register("bridge--haptic", Bridge__HapticController)

import Bridge__LogoController from "./bridge/logo_controller"
application.register("bridge--logo", Bridge__LogoController)

import Bridge__MenuController from "./bridge/menu_controller"
application.register("bridge--menu", Bridge__MenuController)

import Bridge__NotificationTokenController from "./bridge/notification_token_controller"
application.register("bridge--notification-token", Bridge__NotificationTokenController)

import Bridge__TitleController from "./bridge/title_controller"
application.register("bridge--title", Bridge__TitleController)

import Bridge__ToastController from "./bridge/toast_controller"
application.register("bridge--toast", Bridge__ToastController)

import Bridge__VibratorController from "./bridge/vibrator_controller"
application.register("bridge--vibrator", Bridge__VibratorController)

import CardController from "./card_controller"
application.register("card", CardController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DebugController from "./debug_controller"
application.register("debug", DebugController)

import DistanceController from "./distance_controller"
application.register("distance", DistanceController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EntranceController from "./entrance_controller"
application.register("entrance", EntranceController)

import FieldErrorsController from "./field_errors_controller"
application.register("field-errors", FieldErrorsController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import GrowingTextareaController from "./growing_textarea_controller"
application.register("growing-textarea", GrowingTextareaController)

import HeightController from "./height_controller"
application.register("height", HeightController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import MessageController from "./message_controller"
application.register("message", MessageController)

import MessageFormController from "./message_form_controller"
application.register("message-form", MessageFormController)

import PasswordResetEmailController from "./password_reset_email_controller"
application.register("password-reset-email", PasswordResetEmailController)

import PhotosController from "./photos_controller"
application.register("photos", PhotosController)

import PinchController from "./pinch_controller"
application.register("pinch", PinchController)

import ReadableController from "./readable_controller"
application.register("readable", ReadableController)

import ReplaceClassesController from "./replace_classes_controller"
application.register("replace-classes", ReplaceClassesController)

import RoomController from "./room_controller"
application.register("room", RoomController)

import RoomUnreadCountResetController from "./room_unread_count_reset_controller"
application.register("room-unread-count-reset", RoomUnreadCountResetController)

import ScrollLoaderController from "./scroll_loader_controller"
application.register("scroll-loader", ScrollLoaderController)

import SettingsFormController from "./settings_form_controller"
application.register("settings-form", SettingsFormController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)
