default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development.sqlite3
  queue:
    <<: *default
    database: db/development_queue.sqlite3

test:
  primary:
    <<: *default
    database: db/test.sqlite3
  queue:
    <<: *default
    database: db/test_queue.sqlite3

production:
  primary:
    <<: *default
    database: /home/deploy/fresh-dating-app/shared/production.sqlite3
  queue:
    <<: *default
    database: /home/deploy/fresh-dating-app/shared/queue.sqlite3
    migrations_paths: db/queue_migrate
